### ISSUE TITLE
Fatal Error: callback returned unsupported credentials type

### ISSUE THREAD

**Issue by cjb** [surf-build/surf#23]
Hi!  Just trying out surf.
```
 λ npm install -g surf-build
 λ export GITHUB_TOKEN="1111111111111111111111111111111111111111"
 λ surf-build --repo https://github.com/surf-build/surf -s 12efc7bf3888ae4e4cc1a79f28fe6e7cef78d0b1
Fatal Error: callback returned unsupported credentials type
```
Any ideas?  I've double-checked that GITHUB_TOKEN is the correct 40 char token I just generated with repo and gist permissions.  In case it matters, I'm on Ubuntu.  I see that the error string comes from `libgit2/src/transports/ssh.c`.  Thanks!

**Comment by cjb** [comment]
I checked that OS X works fine, it's just Ubuntu failing.

The `unsupported credentials type` it's talking about is `GIT_CREDTYPE_USERPASS_PLAINTEXT`.  Weird.  Is that not what OS X uses too?

**Comment by cjb** [comment]
I compared `DEBUG=*` builds between Linux and OS X:

Linux:
```
  surf:git-api Cloning https://github.com/surf-build/surf => /home/cjb/.config/surf/repos/8174dbe355cb2cc62f872d078e90de3fb805e26b, bare=true +1ms
  surf:git-api Returning 51cc398f5fcfee79cb8d43d61c3f57cc2acafcf2 for authentication token
Fatal Error: callback returned unsupported credentials type
```

OS X:
```
  surf:git-api Cloning https://github.com/surf-build/surf => /Users/cjb/Library/Application Support/surf/repos/8174dbe355cb2cc62f872d078e90de3fb805e26b, bare=true +4ms
  surf:git-api Fetching all refs for /Users/cjb/Library/Application Support/surf/repos/8174dbe355cb2cc62f872d078e90de3fb805e26b +4s
```

So it looks like the first difference is that node-git is calling back into the provided `authentication` callback on Linux, but not on OS X.  I don't know why.  :(  `git clone https://github.com/surf-build/surf` works fine from the Linux command line.

**Comment by cjb** [comment]
Waaaaiiiit a second.  When I'm cloning https://github.com/surf-build/surf, why do I end up in libgit2's **ssh** transport?  No wonder it can't authenticate to github with user/pass over ssh.

**Comment by cjb** [comment]
Oh, this was so my fault.  And the nodegit hackers were very patient with me.  :/

My `.gitconfig` contains:
```
[url "git@github.com:"]
        insteadOf = https://github.com/
```
because golang needs that for `go get` to behave with private github repos.  But it totally hoses surf, which will try to use user/pass creds against SSH as a result.

**Comment by paulcbetts** [comment]
Makes sense!
