### ISSUE TITLE
surf-build in a batch system

### ISSUE THREAD

**Issue by ax3l** [surf-build/surf#39]
Hi,

I would be interested to schedule the `surf-build`s via `surf-client` to an (HPC) batch system (PBS/[Slurm](http://slurm.schedmd.com/slurm.html)/etc.)  via simple job-scripts ([example](https://www.osc.edu/supercomputing/batch-processing-at-osc/job-scripts)).

The reason for that is run-time testing with specific hardware (e.g., Nvidia GPUs, Xeon Phi's, etc.) and specific compilers (e.g., icc, pgi, ...).

Do you have any experience running the builds (not `surf-server`) e.g., on an AWS instance or waiting for them in a batch system to finish? What is the workflow you would suggest to set up such a workflow with distributed `surf-build` instances?

Thanks a lot in advance for any input on that!

ccing @juckel

**Comment by paulcbetts** [comment]
If you need to describe dependencies between jobs (i.e. kick off these jobs on these machines, chill out, run builds on different machines), I'd just script it:

```sh
ssh myuser@host1 -- surf-build -r https://whatever 
ssh myuser@host2 -- surf-build -r https://whatever 
ssh myuser@host3 -- surf-build -r https://whatever
```

The nice thing is, you could even make this your `build.sh` in the repo itself:

```
set -e
if [ -z "$JOB_HOST"] ; then
  ssh myuser@host1 -- env "SURF_SHA1=$SURF_SHA1" "SURF_REPO=$SURF_REPO" surf-build -n "host1"
  ssh myuser@host2 -- env "SURF_SHA1=$SURF_SHA1" "SURF_REPO=$SURF_REPO" surf-build -n "host2" 
else
  // Run the actual build here
fi
```
