### ISSUE TITLE
Surf-server, not there anymore?

### ISSUE THREAD

**Issue by vcsjones** [surf-build/surf#51]
Looking through the documentation, we wanted to use `surf-server` as we expect to use surf kind of heavily.

However, `surf-server` doesn't seem to exist in 1.0.0-beta14.In another comment at https://github.com/surf-build/surf/issues/36#issuecomment-236384487, it looks like surf-server isn't needed anymore.

So to clarify: should we be using surf-server? If not - great. I'll PR some doc fixes. If we are, we can't seem to find it. We get "surf-server: not found", however `surf-run` and `surf-build` work as expected.

**Comment by paulcbetts** [comment]
You don't need it - I changed the way we fetch from GitHub and so it's far more efficient than it used to be, so surf-server was just complication
