### ISSUE TITLE
Discoverers with affinity 0 aren't ignored

### ISSUE THREAD

**Issue by vcsjones** [surf-build/surf#53]
My rough understanding of things is that if a discoverer's affinity is zero, it should not be run. This is at least the case with the danger.js affinity, where zero [is returned for `x.getAffinityForRootDir`](https://github.com/surf-build/surf/blob/00cf8de73acc0f450fa93115c03365048a7ba2fc/src/build-discoverers/danger.js#L21) when the environment variable `SURF_DISABLE_DANGER` says "don't run".

Later on [in `determineBuildCommands`](https://github.com/surf-build/surf/blob/00cf8de73acc0f450fa93115c03365048a7ba2fc/src/build-api.js#L29), we have this block:

```js
    if (affinity && affinity < 1) return acc;

    if (x.shouldAlwaysRun) {
      activeDiscoverers.push({ affinity, discoverer: x});
      return acc;
    }
```

The goal here is that if the affinity is less than one, then we just return what we've accumulated so far.

I think the intention of the if statement `if (affinity && affinity < 1) return acc;` is wrong. Zero is false-y, so the first half of the if check doesn't hold up. We end up with `if (0 && 0 < 1)`, so we don't bail out early.

Since the danger discoverer is marked as `shouldAlwaysRun`, it gets added next to the array of active discovers:

```js
    if (x.shouldAlwaysRun) {
      activeDiscoverers.push({ affinity, discoverer: x});
      return acc;
    }
```

**Comment by vcsjones** [comment]
Commit f37b97c2f8873b903d36a9c24588c12f4185c6bf changed this behavior to do exactly the opposite of what I think it is supposed to do. I don't think that commit is correct.

**Comment by vcsjones** [comment]
I would propose the `if` statement to be:

`if ((affinity && affinity < 1) || affinity === 0)`

I'm not exactly a JavaScript expert, that's the best I could come up with.

**Comment by paulcbetts** [comment]
@vcsjones I think you're right
