### ISSUE TITLE
installation problem on FreeBSD-11

### ISSUE THREAD

**Issue by hannesm** [surf-build/surf#63]
hey, I use node v7.8.0 and npm 4.4.4.  When trying to `npm install -g --unsafe-perm surf-build`, I run into the following issue:

```
CC(target) Release/obj.target/libgit2/vendor/libgit2/src/iterator.o
../vendor/libgit2/src/iterator.c:1459:44: error: no member named 'st_ctime_nsec' in 'struct stat'
iter->entry.ctime.nanoseconds = entry->st.st_ctime_nsec;
                                        ~~~~~~~~~ ^
../vendor/libgit2/src/iterator.c:1462:44: error: no member named 'st_mtime_nsec' in 'struct stat'
iter->entry.mtime.nanoseconds = entry->st.st_mtime_nsec;
                                        ~~~~~~~~~ ^
2 errors generated.
```

This seems to be an issue in `nodegit` - which I can install via `npm install -g --unsafe-perm nodegit` (in version 0.18.0) - where you depend on an older version (0.16.0 AFAICT).  Is there a way to upgrade to the most recent nodegit?  Or any chance #56 will get rebased and merged into master?

I'm not used to npm and node at all (and don't know how to move forward here, i.e. test a build with adjusted dependencies).  Any help is appreciated.

**Comment by mato** [comment]
@hannsem Is there some reason why you can't use node 6.x LTS? I also ran into "unspecified amount of obscure npm errors" with 7.x which is why I ended up using 6.x for my Linux setup of surf, which works fine.

**Comment by hannesm** [comment]
@mato using node v6.10.2 and npm 3.10.10 I run into exactly the same issue - the issue is that nodegit 0.16 does not compile on FreeBSD (see https://github.com/nodegit/nodegit/issues/1160)

**Comment by hannesm** [comment]
and indeed, the solution is to bump 0.16 to 0.18 in package.json!

**Comment by paulcbetts** [comment]
@hannesm I can do the upgrade, yeah - thanks for dropping me a line.

**Comment by paulcbetts** [comment]
1.0.4 is published, you should be all set
