### ISSUE TITLE
surf-install doesn't end up working (OSX), odd failures

### ISSUE THREAD

**Issue by rfay** [surf-build/surf#65]
I did surf-install with

`surf-install -n surf-darwin-ddev -c "surf-run -r https://github.com/drud/ddev -j 1 -- surf-build --name surf-$(go env GOOS)"`

This resulted in a local.surf-ddev.plist as here:
[local.surf-ddev.plist.txt](https://github.com/surf-build/surf/files/1167823/local.surf-ddev.plist.txt)

But when activated with launchctl load, the stderr from that came out like this:
```
$ cat /tmp/surf-ddev-stderr.log
Repository not specified and current directory is not a Git repo
Usage: surf-run -r https://github.com/some/repo -- command arg1 arg2 arg3...
Monitors a GitHub repo and runs a command for each changed branch / PR.

Options:
  -h, --help     Show help                                             [boolean]
  -r, --repo     The URL of the repository to monitor. Defaults to the repo in
                 the current directory
  -j, --jobs     The number of concurrent jobs to run. Defaults to 2
  -v, --version  Print the current version number and exit


Some useful environment variables:

GITHUB_ENTERPRISE_URL - the GitHub Enterprise URL to use instead of .com.
GITHUB_TOKEN - the GitHub (.com or Enterprise) API token to use. Must be
provided.
```

I'm no expert at plist files, but I see nothing wrong with the generated plist file, but obviously surf-run is not being executed as I expect it to be. (I'm having trouble with surf-install on windows also, but I'll make a separate issue if I can figure that out a bit.)

**Comment by paulcbetts** [comment]
I've had a lot of trouble with launchd actually doing what it's documented to :-/   This feature probably needs some work

**Comment by rfay** [comment]
The problem here is that the first argument in ProgramArguments (against all reasonable logic) has to be the program again, as in https://gist.github.com/rfay/1235d1721080bed8280170b6e38dbdd3 - I'll see if I can figure out a PR.
